site_name: 'mescal Package Documentation'
# site_url: 'https://github.com/helgeesch/mescal/'
repo_url: 'https://github.com/helgeesch/mescal/'


theme:
  name: material
  palette:
    primary: 'teal'
    accent: 'amber'
  features:
    - navigation.tabs
    - content.tabs.link
    - navigation.sections

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 5

plugins:
  - search
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [submodules]
          options:
            heading_level: 2
            show_root_heading: true
            show_root_full_path: false
            show_object_full_path: false
            show_root_members_full_path: false
            show_symbol_type_heading: true
            show_category_heading: false
            show_root_toc_entry: false
            show_signature_type_parameters: true
            members_order: source

nav:
  - Core:
    - StudyManager: api_reference/study_manager.md
    - Datasets: api_reference/datasets.md
    - Flag System:
      - Flag: api_reference/flag.md
      - FlagIndex: api_reference/flag_index.md
    - Units: api_reference/units.md
    - Validation: api_reference/validation.md

  - Visualization Modules:
      - TimeSeriesDashboard: api_reference/time_series_dashboard.md
      - Folium Viz System:
        - api_reference/folium_viz_system/index.md
      - Folium Legend System:
        - api_reference/folium_legend_system/index.md
  - Energy Data Handling:
      - api_reference/energy_data_handling/index.md
      - Area Accounting:
        - api_reference/energy_data_handling/area_accounting/index.md
        - Area / Border Model Generators: api_reference/energy_data_handling/area_accounting/model_gen.md
        - Area Variables: api_reference/energy_data_handling/area_accounting/area_variables.md
        - Border Variables: api_reference/energy_data_handling/area_accounting/border_variables.md
      - Model Membership Handling: api_reference/energy_data_handling/model_handling/index.md
      - Variable Utils:
        - api_reference/energy_data_handling/variable_utils/index.md
        - In-common Aggregations: api_reference/energy_data_handling/variable_utils/in_common_aggs.md
        - Up-/Down Directional Aggregations: api_reference/energy_data_handling/variable_utils/direction_aggs.md
        - Congestion Rent: api_reference/energy_data_handling/variable_utils/congestion_rent.md
        - Regional Trade Balance: api_reference/energy_data_handling/variable_utils/regional_trade_balance.md
      - Granularity Modules: api_reference/energy_data_handling/granularity_modules.md
      - Network Lines Data: api_reference/energy_data_handling/network_lines_data.md
      - Time Series Gap Handling: api_reference/energy_data_handling/time_series_gap_handling.md
