name: Test with Vanilla Studies

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-vanilla-studies-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Clone vanilla-studies repo
      run: |
        git clone https://github.com/helgeesch/mescal-vanilla-studies.git
        cd mescal-vanilla-studies
        git rev-parse HEAD > COMMIT_SHA.txt

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install mescal-related packages
      run: |
        # Use PR SHA for mescal if triggered by PR
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          COMMIT_SHA="${{ github.event.pull_request.head.sha }}"
        else
          COMMIT_SHA="${{ github.sha }}"
        fi

        pip install --upgrade pip
        pip install git+https://github.com/helgeesch/mescal@${COMMIT_SHA}
        pip install git+https://github.com/helgeesch/mescal-pypsa
        pip install git+https://github.com/helgeesch/captain-arro

    - name: Install other requirements
      run: |
        cd mescal-vanilla-studies
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run notebook tests
      run: |
        cd mescal-vanilla-studies
        python -m pytest tests/test_notebooks.py -v